# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MoreItems' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for MoreItems

  target 'MoreItemsTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MoreItemsUITests' do
    inherit! :search_paths
    # Pods for testing
  end
 pod 'MJExtension', '~> 3.0.15.1'
 pod 'Masonry', '~> 1.1.0'
 pod 'SDWebImage', '~> 5.0.0-beta3'
end
